# Generated by Django 3.2.10 on 2021-12-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_ormq_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ormq',
        ),
    ]
