# Generated by Django 3.2.10 on 2021-12-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_image_post_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
