# Generated by Django 3.2.10 on 2021-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ormq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='posts/')),
            ],
        ),
    ]
