# Generated by Django 3.2.10 on 2021-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_ormq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
